import type { Metadata } from 'next'
import '../app/globals.css'
import "@/assets/style/App.scss";
import { linksDetails } from '@/shared'
import { Box } from '@mui/material';
import { Footer, Header } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Box
          sx={{
            position: "relative",
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
            justifyContent: "space-between",
          }}
        >
          <Header links={linksDetails} />
          <Box sx={{ flexGrow: 1 }}>
            <main>
              {children}
            </main>
          </Box>
          <Box sx={{ flexGrow: 0 }}>
            <Footer />
          </Box>
        </Box>
      </body>
    </html>
  )
}
